# @package _global_

# Конфигурация для MLflow модели

# Размер входного изображения
image_size:
  height: 200
  width: 200

# Параметры нормализации (ImageNet)
normalize:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Порог для классификации
threshold: 0.5
