# Конфигурация для CNN Baseline модели

# Размер входного изображения
CNN:
  input_size: 200  # Должен соответствовать размеру из data.yaml (image_size.height/width)

  conv1:
    kernel_size: 3
    stride: 1
    padding: 1

  pool1:
    kernel_size: 2
    stride: 2

  conv2:
    kernel_size: 3
    stride: 1
    padding: 1

  pool2:
    kernel_size: 2
    stride: 2
