# @package _global_

# Конфигурация для обучения baseline модели
# Использует baseline_model.yaml вместо model.yaml

defaults:
  - data: ../data/data.yaml
  - model: ../model/baseline_model.yaml
  - training: ../training/training.yaml
  - optimizer: ../optimizer/optimizer.yaml
  - logging: ../logging/logging.yaml
  - trainer: ../trainer/trainer_baseline.yaml
  - _self_

# Общие параметры
seed: 42

# Флаг для определения baseline модели
use_baseline: true
